### ISSUE TITLE
Fir Planks (from Biomes o plenty) side textures are a different block

### ISSUE THREAD

**Issue by Shrimpton** [Ametrin-Studios/BlockVariants#2]
**Describe the bug**
the fir planks slab and stairs blocks i had used them to make a house prior to installing the mod. After installing the mod the sides of the blocks change design, they now look more like ancient debris or palm wood i think.

**Version (please complete the following information):**
 - Minecraft version: [1.18.2]
 - Forge version: [40.1.0]
 - Block Variants version [3.2]

**Comment by Shrimpton** [comment]
![2022-07-05_14 19 45](https://user-images.githubusercontent.com/37606434/177237231-b3962ddf-8016-45b7-a850-fca2c4a50909.png)

**Comment by BarionLP** [comment]
that's really weird, I can't reproduce it.
May be caused by a resource pack

![2022-07-05_07 12 54](https://user-images.githubusercontent.com/76686287/177254252-300d682e-7eeb-4300-81d0-d213bf181cf3.png) 

speaking technically Block Variants has no influence on this, seems like the resource loading messed up
Restart your game (maybe also your full system) and check if it still happens, also try it on a new world.

**Comment by Shrimpton** [comment]
yeah idk, there are alot of resource present on my minecraft with the mod i use (create flavoured). it probably wasn't the fault of block variants cos there were no more resource packs added with install of this i realise now :/  

at this point i don't want to fuck up something by fiddling with all the packs so ill just not use that block and we can close this issue knowing it isnt the modpacks fault.

**Comment by BarionLP** [comment]
you could also update forge, I think there were some fixes regarding resources
